"""empty message

Revision ID: c7b14dc70988
Revises: 
Create Date: 2023-02-02 02:34:21.531208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b14dc70988'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('rutina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('objetivo', sa.String(), nullable=True),
    sa.Column('instrucciones', sa.String(), nullable=True),
    sa.Column('contenido', sa.String(), nullable=True),
    sa.Column('periodicidad', sa.String(), nullable=True),
    sa.Column('inicio', sa.DateTime(), nullable=True),
    sa.Column('terminacion', sa.DateTime(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rutina_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rutina_id'], ['rutina.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paso')
    op.drop_table('rutina')
    op.drop_table('user')
    # ### end Alembic commands ###
